"""empty message

Revision ID: 68eb6c9fe9e1
Revises: bfc4148bcf39
Create Date: 2020-05-23 11:02:29.508404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68eb6c9fe9e1'
down_revision = 'bfc4148bcf39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
